### ISSUE TITLE
action.yml requirements

### ISSUE THREAD

**Issue by mtfoley** [mtfoley/yolo-merge#3]
Need to make sure action.yml has sufficient elements for marketplace

cc @j-dogcoder

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
- [ ] name
- [ ] description
- [ ] inputs
   - [ ] use-last-commit: boolean default to true. If true, only attempt merge when last commit contains "YOLO!" in addition to title containing it.
- [ ] outputs
   - [ ] merged - boolean to equal true if this managed to actually merge
   - [ ] merge-error - string to indicate the error if unable to merge (e.g. not the repo owner, merge conflicts present, etc)
- [ ] runs (for javascript action)
- [ ] branding
  - [ ] color
  - [ ] icon

**Comment by jaspermayone** [comment]
I'll take this one!

**Comment by jaspermayone** [comment]
Won't let me check the boxes cause I am not a contributor, but done! PR #7
